#ifndef __EdViewPanel__
#define __EdViewPanel__

/**
@file
Subclass of ViewPanel, which is generated by wxFormBuilder.
*/

#include "EdGUI.h"

//// end generated include

/** Implementing ViewPanel */
class EdViewPanel : public ViewPanel
{
	public:
		/** Constructor */
		EdViewPanel( wxWindow* parent );
	//// end generated class members

		EdViewPanel( wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize( 494,291 ), long style = wxTAB_TRAVERSAL );
		void OnSize( wxSizeEvent& event );
	
};

#endif // __EdViewPanel__
